feat(v3): add checkbox component on junipero 3
p3ol/junipero pull request #1106
Opened 2022-09-26 18:17 UTC by maximedasilva

2022-09-27 12:07 UTC, dackmin requested changes

2022-09-27 12:07 UTC, dackmin commented on packages/theme/lib/Checkbox.sass
> +    max-width: 100%
add eof

2022-09-29 07:02 UTC, dackmin requested changes

2022-09-29 07:02 UTC, dackmin commented on packages/react/lib/CheckboxField/index.js
> +CheckboxField.displayName = 'Checkbox';
`CheckboxField.displayName = 'CheckboxField';`

2022-09-29 07:10 UTC, dackmin requested changes

2022-09-29 07:10 UTC, dackmin commented on packages/react/lib/CheckboxField/index.js
> +  const [state, dispatch] = useReducer(mockState, {
move state above imperative handle

2022-09-29 07:10 UTC, dackmin commented on packages/react/lib/CheckboxField/index.js
> +  checked = false,
group prop with default values together

2022-09-29 07:10 UTC, dackmin commented on packages/react/lib/CheckboxField/index.js
> +  useEventListener('keypress', e => {
Can't we replace the global keypress event with a keypress handler on the wrapping label (that has the tabIndex) as it will only be triggered when the label is focused? that's pure speculation I don't know if it will work at all, but we could get rid of the global event handler as well as the focus state management altogether

2022-09-29 07:10 UTC, dackmin commented on packages/react/lib/CheckboxField/index.js
> +    if (!disabled) {
avoid superfluous indent

```js
if (disabled) {
  return;
}

...
```

2022-09-29 07:10 UTC, dackmin commented on packages/react/lib/CheckboxField/index.js
> +        'field',
remove field and checkbox classes, use `checkbox-field` (too mush classes like v2 is a pain in the ass when trying to override something down the stream)

2022-09-29 07:10 UTC, dackmin commented on packages/react/lib/CheckboxField/index.test.js
> +});
can you add a test using the `onValidate` prop?

2022-09-29 07:10 UTC, dackmin commented on packages/theme/lib/CheckboxField.sass
> +    max-width: 100%
add eof

2022-09-29 07:55 UTC, maximedasilva commented on packages/react/lib/CheckboxField/index.js
> +        'field',
How do you manage to focus on checkbox on the style file ? We used to use a `.junipero.[component-name]` selector, but by removing those two selectors, selecting a component would become tricky no ?

2022-09-29 07:59 UTC, dackmin commented on packages/react/lib/CheckboxField/index.js
> +        'field',
`.junipero.checkbox-field` 😄

2022-09-29 08:02 UTC, maximedasilva commented on packages/react/lib/CheckboxField/index.js
> +        'field',
Sorry i did not understand your comment at first place, i understood you wanted to remove all field or {component} classes, and not you wanted to replace with checkbox-field. 

Got it

2022-09-29 08:39 UTC, maximedasilva commented on packages/react/lib/CheckboxField/index.js
> +  useEventListener('keypress', e => {
adding a `keyPress` handler on label seems to works and avoid using `focus`state managing too. Nice one.

2022-10-05 07:01 UTC, dackmin approved these changes

2022-10-05 07:01 UTC, merged