✨feat(v3): add radio-button
p3ol/junipero pull request #1133
Opened 2022-10-13 14:39 UTC by maximedasilva

2022-10-13 15:14 UTC, dackmin requested changes

2022-10-13 15:14 UTC, dackmin commented on packages/react/lib/RadioField/index.js
> +  const wrapperRef = useRef();
rename to `innerRef` to be consistent with other components

2022-10-13 15:14 UTC, dackmin commented on packages/react/lib/RadioField/index.js
> +
remove line break

2022-10-13 15:14 UTC, dackmin commented on packages/react/lib/RadioField/index.js
> +
remove line break

2022-10-13 15:14 UTC, dackmin commented on packages/react/lib/RadioField/index.js
> +
remove line break

2022-10-13 15:14 UTC, dackmin commented on packages/react/lib/RadioField/index.js
> +
remove line break

2022-10-13 15:14 UTC, dackmin commented on packages/react/lib/RadioField/index.js
> +    const dirty = true;
remove this and pass true to dispatch directly

2022-10-13 15:14 UTC, dackmin commented on packages/react/lib/RadioField/index.js
> +      id={id}
id is not used anywhere else, remove it from the props and let it be passed with `...rest`

2022-10-13 15:14 UTC, dackmin commented on packages/react/lib/RadioField/index.js
> +          invalid: !state.valid,
```js
classNames(
  ...
  state.dirty ? 'dirty' : 'pristine',
  !state.valid && state.dirty ? 'invalid' : 'valid',
  ...
)
```

2022-10-13 15:14 UTC, dackmin commented on packages/theme/lib/RadioField.sass
> +  &.invalid
`&.invalid.dirty`

2022-10-13 15:23 UTC, maximedasilva commented on packages/react/lib/RadioField/index.js
> +  const wrapperRef = useRef();
event if it exists a innerRefs array used for the options refs ?

2022-10-13 15:28 UTC, maximedasilva commented on packages/react/lib/RadioField/index.js
> +          invalid: !state.valid,
why adding state.dirty here if state.valid already rely on it ?

2022-10-14 11:46 UTC, dackmin commented on packages/react/lib/RadioField/index.js
> +          invalid: !state.valid,
to add styles when not dirty if needed, mostly

2022-10-14 11:47 UTC, dackmin commented on packages/react/lib/RadioField/index.js
> +  const wrapperRef = useRef();
yep, or rename `innerRefs` to `optionsRefs` maybe

2022-10-17 07:47 UTC, maximedasilva commented on packages/react/lib/RadioField/index.js
> +          invalid: !state.valid,
yes I was not very clear, I was speaking about why having `state.dirty` on this condition `state.valid && state.dirty`, not dirty class itself, but with some reflexion it could be useful having this condition even if valid state should change just when field become dirty.
I resolve it

2022-10-18 07:17 UTC, dackmin requested changes

2022-10-18 07:17 UTC, dackmin commented on packages/react/lib/RadioField/index.js
> +      parseValue(value) !== state.value
`state.value` should be the raw value, not the parsed one

2022-10-18 07:17 UTC, dackmin commented on packages/react/lib/RadioField/index.js
> +    dispatch({
transform to one liner

2022-10-18 07:17 UTC, dackmin commented on packages/react/lib/RadioField/index.js
> +    onChange?.({
same

2022-10-18 07:17 UTC, dackmin commented on packages/react/lib/RadioField/index.js
> +    updateControl?.({
same

2022-10-18 07:17 UTC, dackmin commented on packages/react/lib/RadioField/index.js
> +        {
`{ disabled }`

2022-10-18 07:17 UTC, dackmin commented on packages/react/lib/RadioField/index.js
> +            {
```jsx
className={classNames({
  checked: isChecked(option),
  disabled: disabled || option.disabled,
})}
```

2022-10-18 07:17 UTC, dackmin commented on packages/react/lib/RadioField/index.js
> +
add `displayName`

2022-10-19 12:20 UTC, dackmin approved these changes

2022-10-19 12:20 UTC, merged