✨ feat: init Pagination component
p3ol/junipero pull request #1439
Opened 2024-01-17 17:13 UTC by leollorca

This PR init the Pagination component.

Numbers wrap if there is more than 7 pages.

2024-01-18 10:19 UTC, maximedasilva requested changes
Nicely done, but it miss some tests on your component, and the types for your beloved coworkers which now uses typescript <3

2024-01-18 10:19 UTC, maximedasilva commented on packages/react/lib/Pagination/index.js
> +    if (size < 8) {
You can simplify your conditions: 
as many of your conditions are excluding:

```
if (size < 8) {
  ...
} else {
  if( activePage < 5) {
    ...
  } else if (activePage <= size - 4) {
    ...
  } else {
    ...
  }
}
```
As `activePage < 5` and `activePage >= 5` are excluding
and `activePage <= size - 4` and `activePage > size - 4` are excluding and as the length is greater than 8 we can't be in the world of `activePage < 5` and `activePage <= size - 4`

2024-01-18 10:19 UTC, maximedasilva commented on packages/react/lib/Pagination/index.stories.js
> +};
use stoybook action function
```
import { action } from '@storybook/addon-actions';

return <Pagination size={8} onPageChange={action('Page changed')} />
```

2024-01-18 10:19 UTC, maximedasilva commented on packages/react/lib/Pagination/index.stories.js
Maybe add more examples (one with a specific initialPage, and various with each type of length you made)

2024-01-18 10:21 UTC, maximedasilva commented on packages/theme/lib/Pagination.sass
> +
remove this line

2024-01-18 15:47 UTC, leollorca commented on packages/react/lib/Pagination/index.js
> +      }
`Array.from({length: size})` -> That's what I was looking for, thank you!

So now, I think I prefer to use reduce instead of map, can I ?

2024-01-18 15:56 UTC, maximedasilva commented on packages/react/lib/Pagination/index.js
> +      }
Huh how you wish to use reduce ? I don't think this is the best methods for this purpose.

I simplified the method below btw

``` javascript
pageNumbers = Array.from({length: size}).map((_, i) => (
    <div
      key={i}
      onClick={() => goTo(i + 1)}
      className={classNames(
        'junipero',
        'pagination',
        'pagination-item',
        `${i + 1 === activePage ? 'pagination-item-active' : ''}`,
      )}
    >
      {i + 1}
    </div>
  )
)
```

2024-01-18 16:05 UTC, leollorca commented on packages/react/lib/Pagination/index.js
> +      }
I have this with reduce but I'll use map if you still sure it match better for this case

`return Array.from({length: size}).reduce((numbersTags, _, i) => {
        numbersTags.push(
          <div
            key={i + 1}
            onClick={() => goTo(i + 1)}
            className={classNames(
              'junipero',
              'pagination',
              'pagination-item',
              `${
                i + 1 === state.activePage 
                  ? 'pagination-item-active'
                  : ''
              }`,
            )}
          >
            {i + 1}
          </div>
        );

        return numbersTags;
      }, [])`

2024-01-18 16:08 UTC, leollorca commented on packages/react/lib/Pagination/index.js
> +      }
I have this with reduce but I'll use map if you still sure it match better for this case

```
return Array.from({length: size}).reduce((numbersTags, _, i) => {
        numbersTags.push(
          <div
            key={i + 1}
            onClick={() => goTo(i + 1)}
            className={classNames(
              'junipero',
              'pagination',
              'pagination-item',
              `${
                i + 1 === state.activePage 
                  ? 'pagination-item-active'
                  : ''
              }`,
            )}
          >
            {i + 1}
          </div>
        );

        return numbersTags;
      }, [])
```

2024-01-18 16:14 UTC, leollorca commented on packages/react/lib/Pagination/index.js
> +      }
I have this with reduce but I'll use map if you still sure it match better for this case

```javascript
return Array.from({length: size}).reduce((numbersTags, _, i) => {
  numbersTags.push(
    <div
      key={i + 1}
      onClick={() => goTo(i + 1)}
      className={classNames(
        'junipero',
        'pagination',
        'pagination-item',
        `${
          i + 1 === state.activePage 
            ? 'pagination-item-active'
            : ''
        }`,
      )}
    >
      {i + 1}
    </div>
  );

  return numbersTags;
}, [])
```

2024-01-18 16:51 UTC, leollorca commented on packages/react/lib/Pagination/index.js
> +      }
Ok no I see why map is better 👌🏻

2024-01-30 10:07 UTC, maximedasilva requested changes

2024-01-30 10:07 UTC, maximedasilva commented on packages/react/lib/Pagination/index.js
> +        pageNumbersTags.unshift(
Why `unshift` and not `push` before adding the actives pages ?

2024-01-30 10:07 UTC, maximedasilva commented on packages/react/lib/Pagination/index.js
> +        pageNumbersTags.unshift(
I think you can chain and not use this `pageNumbersTags`

2024-01-30 10:07 UTC, maximedasilva commented on packages/react/lib/Pagination/index.js
> +        pageNumbersTags.unshift(
Same here why those unshift, and not adding those elements before the previous ?

2024-01-30 10:07 UTC, maximedasilva commented on packages/react/lib/Pagination/index.js
> +      onPageChange(state.activePage);
Add a conditional chaining, or set this props mandatory on index.d.ts (i personnaly prefer it to be optional)

2024-01-30 10:07 UTC, maximedasilva commented on packages/react/lib/Pagination/index.test.js
> +    const onPageChange = jest.fn();
If you expect nothing from this `jest.fn()` you can remove it.

2024-01-30 10:07 UTC, maximedasilva commented on packages/react/lib/Pagination/index.test.js
> +    const onPageChange = jest.fn();
If you expect nothing from this jest.fn() you can remove it.

2024-01-30 10:07 UTC, maximedasilva commented on packages/react/lib/Pagination/index.test.js
> +    const onPageChange = jest.fn();
If you expect nothing from this jest.fn() you can remove it.

2024-01-30 10:07 UTC, maximedasilva commented on packages/react/lib/Pagination/index.test.js
> +    const onPageChange = jest.fn();
If you expect nothing from this jest.fn() you can remove it.

2024-03-18 15:30 UTC, leollorca commented on packages/react/lib/Pagination/index.js
> +  const goTo = page => dispatch({ activePage: page, wasRenderedOnce: true });
should I throw an error if page is falsy ?

2024-03-18 15:37 UTC, leollorca commented on packages/react/lib/Pagination/index.js
> +        pageNumbersTags.unshift(
It was the more intuitive way to me and to not create an empty array at the beginning, should I change ?

2024-03-18 16:00 UTC, leollorca commented on packages/react/lib/Pagination/index.js
> +      onPageChange(state.activePage);
Can I ignore that if I get rid of wasRenderedOnce?

2024-03-18 16:04 UTC, leollorca commented on packages/react/lib/Pagination/index.js
> +        pageNumbersTags.unshift(
Do you mean something like .unshift/push(elem1, elem2, ... etc) ?

2024-03-19 08:28 UTC, maximedasilva commented on packages/react/lib/Pagination/index.js
> +  const goTo = page => dispatch({ activePage: page, wasRenderedOnce: true });
sounds good to me

2024-03-19 08:28 UTC, maximedasilva commented on packages/react/lib/Pagination/index.js
> +      onPageChange(state.activePage);
if the props `wasRenderedOne` has been removed, you can rid of it

2024-03-19 08:32 UTC, maximedasilva commented on packages/react/lib/Pagination/index.js
> +        pageNumbersTags.unshift(
if you add the first element at beggining, you will not manipulate empty array, and for me its very unintuitive to use multiple `unshift`, because it invert the read

2024-03-19 08:33 UTC, maximedasilva commented on packages/react/lib/Pagination/index.js
> +        pageNumbersTags.unshift(
yep,
or `.push(elmt1).push(elmt2)`

2024-03-19 10:34 UTC, leollorca commented on packages/react/lib/Pagination/index.js
> +    if (state.wasRenderedOnce) {
I'm not sure I can remove it, it occurs a gap between the highlighted page and the showing page

2024-03-19 10:39 UTC, maximedasilva commented on packages/react/lib/Pagination/index.js
> +      onPageChange(state.activePage);
sorry my bad, it was a long time ago.

I was not talking about `state.activePage` but about `onPageChange`

`onPageChange?.(state.activePage)`

2024-03-19 10:41 UTC, maximedasilva commented on packages/react/lib/Pagination/index.js
> +    if (state.wasRenderedOnce) {
can you explain more the problem ?

2024-03-20 09:43 UTC, leollorca commented on packages/react/lib/Pagination/index.js
> +    if (state.wasRenderedOnce) {
I found a way to avoid the gap without this boolean, but I think it was because you can access new state only in next render but I am not sure..

2024-03-28 10:05 UTC, maximedasilva approved these changes

2025-07-22 12:02 UTC, closed without merging