✨ feat: new tag component
p3ol/junipero pull request #436
Opened 2021-02-17 14:22 UTC by defless

<img width="71" alt="Capture d’écran 2021-02-17 à 15 21 09" src="https://user-images.githubusercontent.com/43884154/108217345-c528fa80-7133-11eb-87ae-56895561a498.png">

2021-02-17 14:40 UTC, dackmin requested changes

2021-02-17 14:40 UTC, dackmin commented on packages/junipero/lib/Tag/index.js
> +const Tag = ({ value, className }) => {
`Tag` content should be `children` not a custom property like `value`

2021-02-17 14:40 UTC, dackmin commented on packages/junipero/lib/Tag/index.js
> +const Tag = ({ value, className }) => {
what if I want to add custom props to the underlying `span` element inside `Tag`?

2021-02-17 14:40 UTC, dackmin commented on packages/junipero/lib/Tag/index.js
> +Tag.propTypes = {
`propTypes` before `export`

2021-02-17 14:40 UTC, dackmin commented on packages/junipero/lib/Tag/index.js
> +  return (
`return` is useless, replace with `=> (`

2021-02-17 14:40 UTC, dackmin commented on packages/junipero/lib/Tag/index.styl
> +    color: white
use `$color-white`

2021-02-17 14:40 UTC, dackmin commented on packages/junipero/lib/Tag/index.styl
> +    color: white
move it upwards as it is called on every theme

2021-02-17 14:40 UTC, dackmin commented on packages/junipero/lib/Tag/index.styl
> +  justify-content: center
As it is not displayed as a flex element, I think these are ignored. And because we cant it to be inline or inline-block, we can't use flex either.

2021-02-17 14:40 UTC, dackmin commented on packages/junipero/lib/Tag/index.test.js
> +
remove line break

2021-02-17 15:01 UTC, defless commented on packages/junipero/lib/Tag/index.styl
> +    color: white
not the default one, so how can I identify that case ? Because there's no className specified

2021-02-17 15:03 UTC, dackmin commented on packages/junipero/lib/Tag/index.styl
> +    color: white
yep my bad, you should still specify the default color then

2021-02-17 16:58 UTC, dackmin commented on packages/junipero/lib/Tag/index.js
> +const Tag = ({ className, children, ...rest }) => (
if you just omit children it will be passed inside `...rest` 😄

2021-02-18 13:52 UTC, dackmin requested changes

2021-02-18 13:52 UTC, dackmin commented on packages/junipero/lib/Tag/index.js
> +  <span {...rest} className={classNames('junipero', 'tag', className)}/>
missing space before `/>`

2021-02-18 13:52 UTC, dackmin commented on packages/junipero/lib/Tag/index.js
> +const Tag = ({ className, ...rest }) => (
You can `export default` directly

2021-02-18 13:52 UTC, dackmin commented on packages/junipero/lib/Tag/index.styl
> +  align-items: center
this one is probably not used at all

2021-02-18 13:52 UTC, dackmin commented on packages/junipero/lib/Tag/index.styl
> +  background: $color-alto
Missing `color: $color-midnight` for the default one

2021-02-18 13:54 UTC, defless commented on packages/junipero/lib/Tag/index.styl
> +  background: $color-alto
$color-midnight comes with the 'junipero' class

2021-02-18 14:00 UTC, dackmin commented on packages/junipero/lib/Tag/index.styl
> +  background: $color-alto
:ok_hand:

2021-02-18 14:59 UTC, dackmin approved these changes

2021-02-18 15:00 UTC, merged