✨ feat(dashboard): radio field component
p3ol/junipero pull request #515
Opened 2021-04-21 16:08 UTC by emileNetter

<img width="107" alt="Capture d’écran 2021-04-21 à 18 07 26" src="https://user-images.githubusercontent.com/16649348/115586040-77b04180-a2cc-11eb-9886-01e4ba59bd56.png">
<img width="1035" alt="Capture d’écran 2021-04-21 à 18 07 11" src="https://user-images.githubusercontent.com/16649348/115586046-77b04180-a2cc-11eb-8cb9-58505d39157a.png">

2021-04-21 16:27 UTC, dackmin requested changes

2021-04-21 16:27 UTC, dackmin commented on packages/junipero/lib/RadioField/index.js
> +    inputRef,
missing `internalValue: state.checked, focused: state.focused`

2021-04-21 16:27 UTC, dackmin commented on packages/junipero/lib/RadioField/index.js
> +
remove useless linebreak

2021-04-21 16:27 UTC, dackmin commented on packages/junipero/lib/RadioField/index.stories.js
> +        value='strong'
dumb

2021-04-21 16:27 UTC, dackmin commented on packages/junipero/lib/RadioField/index.styl
> +        line-height: $text-extra-line-height
missing EOF line break

2021-04-21 16:27 UTC, dackmin commented on packages/junipero/lib/ToggleField/index.js
> +      onChange({ value, checked: state.checked });
should not be here

2021-04-21 16:28 UTC, dackmin commented
In addition to my review, this is a breaking change from v1 where you would have supplied an `options` prop to render multiple radio fields. Is there any particular reason you didn't start from v1 RadioField?
@NicolasAuger whatcha think

2021-04-22 13:05 UTC, NicolasAuger requested changes

2021-04-22 13:07 UTC, NicolasAuger commented
The component is nice, i prefer using `opts` for multiple fields too, rather than multiple `<RadioField />` components.

2021-04-27 09:12 UTC, dackmin requested changes

2021-04-28 13:59 UTC, dackmin approved these changes

2021-04-28 14:00 UTC, merged