♻️ refactor: replace enzyme tests with testing-library/react
p3ol/junipero pull request #855
Opened 2022-02-23 11:24 UTC by dackmin

2022-02-23 15:25 UTC, maximedasilva requested changes

2022-02-23 15:25 UTC, maximedasilva commented on packages/junipero/lib/TagsField/index.test.js
> +    jest.useRealTimers();
why those useRealTimers?

2022-03-01 10:10 UTC, dackmin commented on packages/junipero/lib/TagsField/index.test.js
> +    jest.useRealTimers();
to counter each `useFakeTimers`

2022-03-01 10:13 UTC, dackmin commented on babel.config.js
> +        regenerator: true,
yeah it was already there I just moved it upwards as it was the same, but we can safely remove it

2022-03-02 12:40 UTC, merged